### ISSUE TITLE
Expose the ability to download a specific version

### ISSUE THREAD

**Issue by Newbie012** [leinelissen/embedded-postgres#1]
It would've been great if there was the option to choose a specific version of node

**Comment by leinelissen** [comment]
Hey @Newbie012. Thanks for checking this out. Do you mean selecting a Postgres version or specifically a Node version? This project should work with a broad range of Node versions, since it's not compiled against Node directly.

**Comment by Newbie012** [comment]
Sorry for not being explicit. I mean a Postgres version

**Comment by Newbie012** [comment]
I'm thinking about integrating this package with https://github.com/ts-safeql/safeql

Right now, whoever uses SafeQL has to install Postgres on their machine. If I could let them use an embedded Postgres version of their choice (mostly 11, 12, 13, 14), that would be an amazing improvement of the DX 😄

**Comment by leinelissen** [comment]
I'm going to look into this, let me get back to you.

**Comment by leinelissen** [comment]
Hey @Newbie012, I've just released a bunch of binaries for earlier Postgres versions. Let me know what you think.

**Comment by Newbie012** [comment]
Wow this is amazing! Thanks for doing all of that work! ❤️ Once I'll get back from my vacation I'll start working on integrating safeql with this project.

**Comment by leinelissen** [comment]
No worries at all, I look forward to your work. In the meanwhile, I will close this issue, but do reach out if you run into things or also if you don't ;).
