### ISSUE TITLE
pg seems to be cjs

### ISSUE THREAD

**Issue by KagChi** [leinelissen/embedded-postgres#12]
import { Client } from 'pg';
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module 'pg' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

**Comment by leinelissen** [comment]
Hey sorry for taking a bit of time for this and thanks for reporting it! This issue is now fixed and new versions are being released to NPM as we speak.
