### ISSUE TITLE
start() never resolves if locale is not English

### ISSUE THREAD

**Issue by andym991** [leinelissen/embedded-postgres#15]
Firstly thank you for your efforts on this repo!

In the `start()` method there's this guard that resolves the promise once the instance has successfully started: 

```
                // GUARD: Check for the right message to determine server start
                if (message.includes('database system is ready to accept connections')) {
                    resolve();
                }
```

but if your PC is not using an English locale and you don't specify an English locale manually by using 
```
process.env.LC_MESSAGES = 'en_US.UTF-8';
```
 then Postgres will log in your PC's locale, which means `database system is ready to accept connections` is never logged and the promise is never resolved.

It's easily solved by forcing Postgres into an English locale - but is there any other implementation that could remove the need for a specific log line? Or a README update to highlight this would be useful! Thanks!

**Comment by leinelissen** [comment]
I've created a pull request with that particular fix. If you could try it out and confirm the fix, I'll try and get it merged.

**Comment by andym991** [comment]
Ah amazing thank you. I can't really think of any other approach honestly so that looks sensible. We'll try it out soon and get back to you
